<template>
    <div class="container">
        <draggable class="list-group"  
            v-model="listAll"
            group="group" 
            :moved="moved" 
            @change="changeList"
            >
            <div v-for="(item,i) in listAll" :key="i">
                <p class="list-group-item" @click="showList(i,listAll)" 
                    :style="{backgroundColor:item.bgColor}">
                    {{item.identifier}}
                </p>
                <ul class="computer-list" :ref="`list${i}`" v-show="item.showList && item.list.length>0">
                    <li class="computer-item" v-for="(listItem,k) in item.list" :key="k">
                        {{listItem.ip}}
                    </li>
                </ul>
            </div>
        </draggable>
    </div>
</template>
<script>
import draggable from 'vuedraggable'
export default {
    name:'roomInfo',
    display:"Two Lists",
    order:1,
    components:{
        draggable
    },
    data(){
        return {
            listOne:[
                {
                    name:'TC9-1-1',
                    id:'TC9-1-1',
                    identifier:'1-1',
                    row:1,
                    showList:false,
                    bgColor:'rgb(95, 187, 169)',
                    list:[
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-1-2',
                    id:'TC9-1-2',
                    identifier:'1-2',
                    row:1,
                    showList:false,
                    bgColor:'rgb(95, 187, 169)',
                    list:[
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-1-3',
                    id:'TC9-1-3',
                    identifier:'1-3',
                    row:1,
                    showList:false,
                    bgColor:'rgb(95, 187, 169)',
                    list:[
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-1-4',
                    id:'TC9-1-4',
                    row:1,
                    identifier:'1-4',
                    showList:false,
                    bgColor:'rgb(95, 187, 169)',
                    list:[
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-2-1',
                    id:'TC9-2-1',
                    showList:false,
                    row:1,
                    identifier:'2-1',
                    bgColor:'rgb(217, 83, 79)',
                    list:[
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-1-5',
                    id:'TC9-1-5',
                    identifier:'1-5',
                    row:1,
                    showList:false,
                    bgColor:'rgb(217, 83, 79)',
                    list:[
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-1-6',
                    id:'TC9-1-6',
                    showList:false,
                    identifier:'1-6',
                    bgColor:'rgb(217, 83, 79)',
                    list:[
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-1-7',
                    id:'TC9-1-7',
                    showList:false,
                    identifier:'1-7',
                    bgColor:'rgb(217, 83, 79)',
                    list:[
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-1-8',
                    id:'TC9-1-8',
                    identifier:'1-8',
                    showList:false,
                    bgColor:'rgb(95, 187, 169)',
                    list:[
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.10',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-3-2',
                    id:'TC9-3-2',
                    identifier:'3-2',
                    showList:false,
                    bgColor:'rgb(95, 187, 169)',
                    list:[
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.20',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-2-3',
                    id:'TC9-2-3',
                    showList:false,
                    identifier:'2-3',
                    bgColor:'rgb(95, 187, 169)',
                    list:[
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.30',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-3-4',
                    id:'TC9-3-4',
                    identifier:'3-4',
                    showList:false,
                    bgColor:'rgb(95, 187, 169)',
                    list:[
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'10,2.1.40',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-4-1',
                    id:'TC9-4-1',
                    identifier:'4-1',
                    showList:false,
                    bgColor:'rgb(217, 83, 79)',
                    list:[
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.10',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-4-2',
                    id:'TC9-4-2',
                    showList:false,
                    identifier:'4-2',
                    bgColor:'rgb(217, 83, 79)',
                    list:[
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.20',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-4-3',
                    id:'TC9-4-3',
                    identifier:'5-3',
                    showList:false,
                    bgColor:'rgb(217, 83, 79)',
                    list:[
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.30',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                },
                {
                    name:'TC9-4-4',
                    id:'TC9-4-4',
                    identifier:'5-4',
                    showList:false,
                    bgColor:'rgb(217, 83, 79)',
                    list:[
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },

                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        },
                        {
                            ip:'20,2.1.40',
                            SN:'123456',
                            id:'1'
                        }
                    ]
                }
            ],
            screenWidth:window.screen.width,
            screenHeight:window.screen.height,
            listAll:[],
        }
    },
    methods:{
        changeList(evt){
            console.log(evt);

            let newIndex = evt.moved.newIndex;
            let oldIndex = evt.moved.oldIndex;
            
            let oldIdentifiterRow =  
                parseInt(oldIndex / 30) + (oldIndex % 30 == 0 ? 1 : oldIndex % 30)
            if (oldIndex > this.listOne.length) {
                var oldIdentifiterCol = this.listAll[oldIndex].identifier.split('-')[1]
                console.log(oldIdentifiterCol,'oldIdentifiterCol');
            }else{
                var oldIdentifiterCol = this.listOne[oldIndex].identifier.split('-')[1]
            }       
            
            let newIdentifiterRow = 
                parseInt(newIndex / 30) + (newIndex % 30 < 30 ? 1 : newIndex % 30)
           

            if (newIndex > this.listOne.length) {
                var newIdentifiterCol = this.listAll[newIndex].identifier.split('-')[1]
            }else{
                var newIdentifiterCol = this.listOne[newIndex].identifier.split('-')[1]
            }

            let item = this.listAll[newIndex-1< 0 ? 0 : newIndex-1];
            let itemO = this.listAll[newIndex+1]
            let itemMove = this.listAll[newIndex]
            let resetArr = [];
            
            
           console.log(this.listAll[oldIndex]);
         
        },
        showList(index,list){
            list[index].showList = !list[index].showList
        },
        removeStart(evt){
            let oldIdentifier = this.listOne[evt.oldIndex].identifier;
           
        },
        removeEnd(evt){
            // console.log(evt,'===');
            let identifier = this.listOne[evt.oldIndex].identifier
            let newIdentifiterRow = parseInt(evt.newIndex / 30) + (evt.newIndex % 30 == 0 ? 1 : evt.newIndex % 30)
            let newIdentifiterCol = this.listOne[evt.oldIndex].identifier.split('-')[1]

        },
        updateList(evt){
            console.log(evt,'updateList');
        },
        moved(ev){
            console.log(ev,'evmove');
        },
        computedWidthSquare(){
            let len = Math.floor(this.screenWidth / 120)
            let numLen = Math.floor(this.screenHeight / 70)
            let result = Math.floor(len * numLen / 4)
            for (let i = 1; i <= len; i++) {
                for (let j = 1; j <= 30; j++) {
                   let obj = {
                        name:'',
                        id:'',
                        identifier:i+'-'+j,
                        showList:false,
                        color:'',
                        bgColor:'#f4f4f4',
                        list:[]
                    }
                    this.listAll.push(obj)
                }

            }
        },
        insertList(){
            for (let i = 0; i < this.listOne.length; i++) {
               let row = this.listOne[i].identifier.split('-')[0];
               let col = this.listOne[i].identifier.split('-')[1]
               let index = (row-1) * 30 + Number(col) - 1;
               if (this.listOne[i].identifier == this.listAll[index].identifier ) {
                   this.listAll[index] = this.listOne[i]
               }
            }
        }

    },
    watch:{
       
    },
    created(){
        this.computedWidthSquare()
        this.insertList()
    }
}
</script>
<style lang="scss" scoped>
    .container{
         width:3600px;
        display: flex;
        flex-wrap: wrap;

    }
    .list-group{
       
        display: flex;
        flex-wrap: wrap;
        .list-group-item{
            display: inline-block;
            width:100px;
            height:50px;
            line-height: 50px;
            color:#111;
            margin: 10px;
            text-align: center;
            cursor: pointer;
        }
       .computer-item{
           text-align: center;
           line-height: 2;
           cursor: pointer;
       }
    }
</style>
